name: Suzannah
favicon: null
layout_spectrum: 0.71896
typography_spectrum: 0.6205
title: Suzannah Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d8d8'
    - '#000000'
    - '#353535'
    - '#6a6a6a'
    - '#909090'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
