name: Suzannah
favicon: null
layout_spectrum: 0.74887
typography_spectrum: 0.9424772365018725
title: Suzannah Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.02403283747844398
  lightness: 0.5669552236795425
  saturation: 0.9403633214533329
  rhythmicContrast: 0.727659119758755
purpose: []
