name: Suzannah
favicon: null
layout_spectrum: 0.456888577202335
typography_spectrum: 0.6465525852981955
title: Suzannah Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.45166478282772005
  lightness: 0.36631072289310396
  saturation: 0.5713388025760651
  rhythmicContrast: 0.10364654147997499
purpose: []
